secret_key_base: 'some_key'
db:
  name: 'db_name'
  host: 'localhost'
  port: '5432'
  username: 'db_username'
  password: 'your_password'
redis:
  cable_url: 'redis_url'
encryption_key: 'encryption_key'
basic_auth:
  login: 'login'
  password: 'password'
jwt:
  access_token_exp: 86400 # 24h time in seconds
  refresh_token_exp: 604800 # 1 week time in seconds
honeybadger:
  api_key: 'some_key'
cookie_store:
  access_token_exp: 4320 # 3 days time in minutes
mailer:
  address: 'address'
  port: 'port'
  domain: 'domain'
  user_name: 'email'
  password: 'password'
