default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["POSTGRES_HOST"] || Rails.application.credentials.dig(:db, :host) %>
  port: <%= ENV["POSTGRES_PORT"] || Rails.application.credentials.dig(:db, :port) %>
  pool: <%= ENV["RAILS_MAX_THREADS"] || Rails.application.credentials.dig(:db, :max_treads) || 5 %>
  username: <%= ENV["POSTGRES_USERNAME"] || ENV['DB_USERNAME'] || Rails.application.credentials.dig(:db, :username) %>
  password: <%= ENV["POSTGRES_PASSWORD"] || ENV['DB_PASSWORD'] || Rails.application.credentials.dig(:db, :password) %>

development:
  <<: *default
  database: github_searcher_by_nickname_development

test:
  <<: *default
  database: github_searcher_by_nickname_test

production:
  <<: *default
  database: github_searcher_by_nickname_production
  username: github_searcher_by_nickname
  password: <%= ENV["GITHUB_SEARCHER_BY_NICKNAME_DATABASE_PASSWORD"] %>
