default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: github_searcher_by_nickname_development

test:
  <<: *default
  database: github_searcher_by_nickname_test

production:
  <<: *default
  database: github_searcher_by_nickname_production
  username: github_searcher_by_nickname
  password: <%= ENV["GITHUB_SEARCHER_BY_NICKNAME_DATABASE_PASSWORD"] %>
